baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'permanent-shadow'
theme = 'paper'

# home page profile
avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
name = 'pc84'
bio = 'artist, husband, zinester, oddball developer'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
