baseURL = 'https://sageandpine.github.io/'
languageCode = 'en-us'
title = 'permanent-shadow'
theme = 'paper'

[params]
  # home page profile
  avatar = 'https://pc84.xyz/wp-content/gallery/glitch-code-digital/Concentric.png?t=1683513537'   # gravatar email or image url
  name = 'pc84'
  bio = 'artist, husband, zinester, oddball developer'

[caches]
  [caches.images]
    # dir = ':cacheDir/images'
    dir = ':cacheDir/img'
